---
- name: Install required packages for docker
  apt:
    name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release']
    state: latest

- name: Copy the docker.list file over
  copy:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list

- name: Retrieve the docker gpg key
  get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Install docker packages
  apt:
    update_cache: yes
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest

- name: Copy over docker files 
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Reload daemons
  systemd:
    daemon_reload: yes

- name: Restart docker
  service:
    name: docker
    state: restarted
